/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/**
 *
 * @author sahir
 */
public class plantillaPrincipal extends javax.swing.JFrame {

   
    public plantillaPrincipal() {
        
        initComponents();
        setLocationRelativeTo(null);
        

         blanco.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            calculateResult();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            calculateResult();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            calculateResult();
        }
    });

        amarrillo.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            calculateResult();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            calculateResult();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            calculateResult();
        }
    });
    
    
        RecaudoXpedidosEntregados.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            resultado2();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            resultado2();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
           resultado2();
        }
    });

        pagoXtransferencia.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            resultado2();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            resultado2();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            resultado2();
        }
    });
        
        naranja.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            resultado3();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            resultado3();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
           resultado3();
        }
    });

        verde.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            resultado3();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            resultado3();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            resultado3();
        }
    });
    
    


          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pagoXtransferencia = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        blanco = new javax.swing.JTextField();
        RecaudoXpedidosEntregados4 = new javax.swing.JTextField();
        RecaudoXpedidosEntregados5 = new javax.swing.JTextField();
        naranja = new javax.swing.JTextField();
        RecaudoXpedidosEntregados = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        verde = new javax.swing.JTextField();
        RecaudoXpedidosEntregados10 = new javax.swing.JTextField();
        PdeEfectividad = new javax.swing.JTextField();
        amarrillo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        label1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(116, 27, 71));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Avanty storage & Logistic");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PAGO X TRANSFERENCIA");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel3.setPreferredSize(new java.awt.Dimension(250, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 250, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RECAUDO X PEDIDOS ENTREGADOS");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 250, 30));

        jPanel1.setBackground(new java.awt.Color(241, 194, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RENDIMIENTO DE ENTREGA");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 250, 30));

        pagoXtransferencia.setBackground(new java.awt.Color(0, 255, 255));
        pagoXtransferencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pagoXtransferencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pagoXtransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoXtransferenciaActionPerformed(evt);
            }
        });
        pagoXtransferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pagoXtransferenciaKeyReleased(evt);
            }
        });
        getContentPane().add(pagoXtransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 90, 30));

        Total.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 90, 30));

        blanco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        blanco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blancoActionPerformed(evt);
            }
        });
        getContentPane().add(blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 90, 30));

        RecaudoXpedidosEntregados4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RecaudoXpedidosEntregados4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(RecaudoXpedidosEntregados4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 90, 30));

        RecaudoXpedidosEntregados5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RecaudoXpedidosEntregados5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(RecaudoXpedidosEntregados5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 90, 30));

        naranja.setBackground(new java.awt.Color(255, 153, 0));
        naranja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        naranja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        naranja.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        naranja.setEnabled(false);
        naranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naranjaActionPerformed(evt);
            }
        });
        getContentPane().add(naranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 90, 30));

        RecaudoXpedidosEntregados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RecaudoXpedidosEntregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecaudoXpedidosEntregadosActionPerformed(evt);
            }
        });
        RecaudoXpedidosEntregados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RecaudoXpedidosEntregadosKeyReleased(evt);
            }
        });
        getContentPane().add(RecaudoXpedidosEntregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 90, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TOTAL");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel6.setPreferredSize(new java.awt.Dimension(250, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 250, 30));

        verde.setBackground(new java.awt.Color(0, 255, 0));
        verde.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        verde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 90, 30));

        RecaudoXpedidosEntregados10.setBackground(new java.awt.Color(255, 0, 0));
        RecaudoXpedidosEntregados10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RecaudoXpedidosEntregados10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(RecaudoXpedidosEntregados10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 90, 30));
        RecaudoXpedidosEntregados10.getAccessibleContext().setAccessibleName("");

        PdeEfectividad.setBackground(new java.awt.Color(201, 218, 248));
        PdeEfectividad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PdeEfectividad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(PdeEfectividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 90, 30));

        amarrillo.setBackground(new java.awt.Color(255, 255, 0));
        amarrillo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amarrillo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amarrillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amarrilloActionPerformed(evt);
            }
        });
        getContentPane().add(amarrillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Efectividad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 90, 20));

        label1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 90, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PAGO X TRANSFERENCIA");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel7.setPreferredSize(new java.awt.Dimension(250, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 250, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RECAUDO X PEDIDOS ENTREGADOS");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 250, 30));

        jPanel3.setBackground(new java.awt.Color(241, 194, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RENDIMIENTO DE ENTREGA");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel9.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 250, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("TOTAL");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel10.setPreferredSize(new java.awt.Dimension(250, 30));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 250, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Jair Piña");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 680));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Guia", "Cliente", "Bruto", "Urbancillos", "Neto", "Telefonos", "Barrios", "Producto", "Novedad", "Novedad2", "Novedad3", "Novedad4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 1140, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void naranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naranjaActionPerformed
        
    }//GEN-LAST:event_naranjaActionPerformed

    private void amarrilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amarrilloActionPerformed
        calculateResult();
    }//GEN-LAST:event_amarrilloActionPerformed

    private void blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blancoActionPerformed
        calculateResult();
    }//GEN-LAST:event_blancoActionPerformed

    private void RecaudoXpedidosEntregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecaudoXpedidosEntregadosActionPerformed
       resultado2();
    }//GEN-LAST:event_RecaudoXpedidosEntregadosActionPerformed

    private void pagoXtransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoXtransferenciaActionPerformed
        resultado2();
    }//GEN-LAST:event_pagoXtransferenciaActionPerformed

    private void RecaudoXpedidosEntregadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecaudoXpedidosEntregadosKeyReleased
         DecimalFormat df = new DecimalFormat("#,###");
 
        if (RecaudoXpedidosEntregados.getText().length() >= 1) {
 
            RecaudoXpedidosEntregados.setText( df.format(Integer.valueOf(RecaudoXpedidosEntregados.getText().replace(".", ""))) );
 
        }
    }//GEN-LAST:event_RecaudoXpedidosEntregadosKeyReleased

    private void pagoXtransferenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagoXtransferenciaKeyReleased
      DecimalFormat df = new DecimalFormat("#,###");
 
        if (pagoXtransferencia.getText().length() >= 1) {
 
            pagoXtransferencia.setText( df.format(Integer.valueOf(pagoXtransferencia.getText().replace(".", ""))) );
 
        }
    }//GEN-LAST:event_pagoXtransferenciaKeyReleased

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

private void calculateResult() {
    String textValue1 = blanco.getText();
    String textValue2 = amarrillo.getText();

    try {
        // Obtener los valores ingresados en los campos de texto
        int value1 = Integer.parseInt(textValue1);
        int value2 = Integer.parseInt(textValue2);

        if (value1 < 0 || value2 < 0) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese números positivos");
            return; // Sale del método si se ingresan números negativos
        }

        // Realizar la operación (en este caso, suma)
        int result = value1 + value2;

        // Mostrar el resultado en el campo de texto de resultado
        naranja.setText(String.valueOf(result));

        // Limpiar el mensaje de error si se había mostrado previamente
        JOptionPane.getRootFrame().dispose();

    } catch (NumberFormatException e) {
        //JOptionPane.showMessageDialog(null, "Por favor, ingrese números válidos");
    }
}

private void resultado2() {
    String textValue1 = RecaudoXpedidosEntregados.getText().replaceAll("\\.", "");
    String textValue2 = pagoXtransferencia.getText().replaceAll("\\.", "");

    try {
        // Obtener los valores ingresados en los campos de texto
        int value1 = Integer.parseInt(textValue1);
        int value2 = Integer.parseInt(textValue2);

        if (value1 < 0 || value2 < 0) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese números positivos");
            return; // Sale del método si se ingresan números negativos
        }

        // Realizar la operación (en este caso, suma)
        int result = value1 + value2;

        // Formatear el resultado con separador de miles si supera las tres cifras
        NumberFormat numberFormat = NumberFormat.getInstance();
        String formattedResult = numberFormat.format(result);

        // Mostrar el resultado en el campo de texto de resultado
        Total.setText(("$ ")+ formattedResult);

        // Limpiar el mensaje de error si se había mostrado previamente
        JOptionPane.getRootFrame().dispose();

    } catch (NumberFormatException e) {
        // JOptionPane.showMessageDialog(null, "Por favor, ingrese números válidos");
    }
}




private void resultado3() {
    String textValue1 = naranja.getText();
    String textValue2 = verde.getText();

    try {
        // Obtener los valores ingresados en los campos de texto
        int value1 = Integer.parseInt(textValue1);
        int value2 = Integer.parseInt(textValue2);

        if (value1 < 0 || value2 < 0) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese números positivos");
            return; // Sale del método si se ingresan números negativos
        }

        // Realizar la operación (en este caso, porcentaje de efectividad)
        int result = value1 / value2*100;

        // Mostrar el resultado en el campo de texto de resultado
        PdeEfectividad.setText(String.valueOf(result+("%")));

        // Limpiar el mensaje de error si se había mostrado previamente
        JOptionPane.getRootFrame().dispose();

    } catch (NumberFormatException e) {
        //JOptionPane.showMessageDialog(null, "Por favor, ingrese números válidos");
    }
}






    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plantillaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plantillaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plantillaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plantillaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plantillaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PdeEfectividad;
    private javax.swing.JTextField RecaudoXpedidosEntregados;
    private javax.swing.JTextField RecaudoXpedidosEntregados10;
    private javax.swing.JTextField RecaudoXpedidosEntregados4;
    private javax.swing.JTextField RecaudoXpedidosEntregados5;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField amarrillo;
    private javax.swing.JTextField blanco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField label1;
    private javax.swing.JTextField naranja;
    private javax.swing.JTextField pagoXtransferencia;
    private javax.swing.JTextField verde;
    // End of variables declaration//GEN-END:variables
}
